name: Community Contribution Label

on:
    workflow_call:
      secrets:
          token:
            required: true
jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            repository: iamshobhraj/.github
            path: .github-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Debug Environment
        run: |
            if [ -f "$GITHUB_EVENT_PATH" ]; then echo "Event path exists"; else echo "Event path missing"; fi
            if [ -n "$token" ]; then echo "Token is set"; else echo "Token is missing"; fi

      - name: Add/Remove Community Contribution Label
        run: python .github-repo/scripts/community-contribution-label.py
        env:
          token: ${{ secrets.token }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}